Mapping validation
interactive-instruments/xtraplatform-spatial pull request #31
Opened 2020-11-02 10:01 UTC by ulugbek

2020-11-02 10:35 UTC, azahnen requested changes

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                if (!columnExists(relation.getSourceField(), relation.getSourceSortKey())) {
The second parameter should be `relation.getSourceContainer()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                if (!columnExists(relation.getTargetField(), relation.getSourceSortKey())) {
The second parameter should be `relation.getTargetContainer()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +
Repeat check with column `relation.getSourceSortKey()` and table `relation.getSourceContainer()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                    if (!columnExists(relation.getJunctionSource().get(), relation.getJunctionTarget().get())) {
The second parameter should be `relation.getJunction().get()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                if (relation.getJunctionSource().isPresent() && relation.getJunctionTarget().isPresent()) {
The second presence check should be `relation.getJunction().isPresent()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
Repeat check with column `relation.getJunctionTarget()` and table `relation.getJunction()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                if (!isColumnUnique(relation.getSourceField(), relation.getSourceSortKey())) {
The first parameter should be `relation.getSourceSortKey()`, the second `relation.getSourceContainer()`.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +                if (!isColumnUnique(relation.getTargetField(), relation.getSourceSortKey())) {
Remove this check.

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
>                  }
Add similar check with `attribute.isTemporal()` (maybe you have to pull, I added this later) and `isColumnTemporal` (to implement, see interactive-instruments/ldproxy#260).

2020-11-02 10:35 UTC, azahnen commented on xtraplatform-feature-provider-sql/src/main/java/de/ii/xtraplatform/feature/provider/sql/infra/db/SqlTypeInfoValidator.java
> +        return column.isPresent() && (column.get().isPartOfPrimaryKey() || column.get().isPartOfUniqueIndex());
I think `isPartOf` might not be strict enough, the index should contain only this column.

For primary key you can check that on the table: 

```
table.getPrimaryKey().getColumns().size() == 1 && table.getPrimaryKey().getColumns().get(0).getReferencedColumn().equals(column)
```

For unique indexes you would have to iterate over `table.getIndexes()`, filter by `isUnique()` and then check like above that `getColumns()` only contains the given `column`.

2020-11-03 09:40 UTC, ulugbek commented
All the issues have been fixed.

2020-11-04 10:27 UTC, azahnen approved these changes

2020-11-26 15:22 UTC, azahnen approved these changes

2020-11-26 15:23 UTC, merged